"""add unique constraint on orders user game

Revision ID: 194dde1ed196
Revises: fce130cdf4a9
Create Date: 2026-08-22 16:43:16.557292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '194dde1ed196'
down_revision: Union[str, Sequence[str], None] = 'fce130cdf4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_orders_user_game', 'orders', ['user_id', 'game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_user_game', 'orders', type_='unique')
    # ### end Alembic commands ###
