"""add role to users

Revision ID: fce130cdf4a9
Revises: a56931f8da0b
Create Date: 2026-08-22 15:58:50.658221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fce130cdf4a9'
down_revision: Union[str, Sequence[str], None] = 'a56931f8da0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    roles_enum = sa.Enum("user", "admin", name="roles")
    roles_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='roles'), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum(name="roles").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
